### ISSUE TITLE
NixOS Support

### ISSUE THREAD

**Issue by LemonjamesD** [Vencord/Installer#38]
Support for NixOS

**Comment by Vendicated** [comment]
Please elaborate. What needs to be done from our side to make this happen? Will you contribute this feature?

**Comment by LemonjamesD** [comment]
Probably just needs a nix flake, I am not that familiar with making them so I probably can't help with that. The way Nix works doesn't allow you to just run the Linux sh script. You can set up a standard build derivative and make sure it requires discord to be installed and then run it and it should* work.

*I have no clue what other kinks it will have.

**Comment by Henry-Hiles** [comment]
NixOS is actually getting very popular, it is a developers dream. However, it is very easy to make a flake, once I switch to NixOS I'll see if I can make one.

**Comment by LemonjamesD** [comment]
> NixOS is actually getting very popular, it is a developers dream. However, it is very easy to make a flake, once I switch to NixOS I'll see if I can make one.

You can make a flake and probably just make a PR to the nixpkgs repo and get it accepted, not sure how fast or what the exact process is.

**Comment by HeapUnderfl0w** [comment]
@LemonjamesD if you dont mind some hacky scripting stuff, you can get Vencord running with a out-of-tree module and some scripting. 

I personally use the setup that i install Discord via `environment.systemPackages` with the openAsar override (`(discord.override { withOpenASAR = true; })`).

Then or the out-of-tree package i use a simple overlay with a dumb derivation fetching the latest release:

```nix
{ buildGoModule, fetchFromGitHub, lib }:
let
  version = "1.2.8";
in
buildGoModule {
  pname = "VencordInstallerCli";
  version = version;

  src = fetchFromGitHub {
    owner = "Vencord";
    repo = "Installer";
    rev = "v${version}";
    sha256 = "sha256-xbJ6ZfaUvjgVC7hBvmYan+AqZZQvdUL69iCteLGsn2A=";
  };

  vendorHash = "sha256-r0T9GF3FyZ+476DkpRZM/zoerVtG4zQIAIeg9E82cXs=";

  ldflags = ["-s" "-w" "-X main.InstallerGitHash=v${version}" "-X main.InstallerTag=v${version}"];
  tags = ["static" "cli"];
}
```

and

```nix
final: prev:
{
    vencord-cli = prev.lib.callPackage ./vencord-cli.nix {};
}
```

And then i use this script in a folder in my homedir to create a patched Discord  that i can run:

```bash
#!/usr/bin/env bash

set -euo pipefail

# Adjust for new discord releases
DISDIR="/nix/store/r2nx5gvjv71598w9ibb6lji5xcxji6pq-discord-0.0.26"
CURDIR="$(readlink -f $(dirname "$0"))/store"

rm -Rf "$CURDIR"
mkdir "$CURDIR"

set -x

cp -R "$DISDIR/"* "$CURDIR/"
chmod -R u+w "$CURDIR"
sed -i "s|$DISDIR/|$CURDIR/|g" "${CURDIR}/opt/Discord/Discord"
VencordInstaller -update
printf "1\n%s\n" "$CURDIR/opt/Discord" | VencordInstaller -install
```

Ive tried for a while to get it to patch the `/nix/store` version, but it didnt quite work due to how the Installer downloads and caches its patch files.
(In addition it doesnt make too much sense to do so either, as Vencord is a super fast moving target which would make
the installed version outdated fast).

**Comment by jsw08** [comment]
Support has already been added on the nixpkgs side. Webcord-vencord is now a package in the nixos unstable branche.

**Comment by LemonjamesD** [comment]
Closing as this is resolved.
